import { Router } from 'express';
import userRouter from './userRouter.js';
import productRouter from './product/productRouter.js';
import cartRouter from './cartRouter.js';
import orderRouter from './orderRouter.js';
import CategoryRouter from './categoryRouter.js';
import variantRouter from './product/variantRouter.js';
import productSpecsRouter from './product/specificationRouter.js';
import productDimensionsRouter from './product/dimensionsRouter.js';
import wishlistRouter from './product/wishlistRouter.js';
const router = Router();
router.use('/user', userRouter);
router.use('/product', productRouter);
router.use('/wishlist', wishlistRouter);
router.use('/category', CategoryRouter);
router.use('/cart', cartRouter);
router.use('/order', orderRouter);
router.use('/variant', variantRouter);
router.use('/product-specs', productSpecsRouter);
router.use('/product-dimensions', productDimensionsRouter);

export default router;
